'use client'
import './globals.css'
// import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { PersistGate } from 'redux-persist/integration/react'; // Import PersistGate
import { persistor } from '../lib/redux/store/store';
import WithPageAccessControl from '@/components/helpers/WithPageAccessControl'
import withAuth from '@/components/helpers/WithAuthen';
import { Providers } from '../lib/redux/providers'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

const roboto = Roboto({ weight: ['300', '400', '500', '700'], subsets: ["cyrillic"] });

/* export const metadata = {
  title: 'Operation Webapp',
  description: 'Generated by create next app',
  viewport: "initial-scale=1, width=device-width"
} */

export default function RootLayout({ children }) {
  const ProtectedChildren = WithPageAccessControl(() => children);
  const AuthProtectedChildren = withAuth(ProtectedChildren);

  return (
    // <AuthProvider>
    <Providers>
      <html lang="en">
        <head>
          <title>Operation</title>
        </head>
        <body className={`${roboto.className} m-0`}>
          <PersistGate loading={null} persistor={persistor}>
            <AppRouterCacheProvider options={{ enableCssLayer: true }}>
              <AuthProtectedChildren />
            </AppRouterCacheProvider>
            {/* {children} */}
          </PersistGate>
        </body>
      </html>
    </Providers>
    // </AuthProvider>
  );
}
